blog/web/views.py
from flask import Blueprint, render_template, session

from back.models import Article, User, ArticleType

web_blue = Blueprint('web', __name__)


@web_blue.route('/index/')
def index():
    user_id = session['user_id']
    user = User.query.get(user_id)
    articles = Article.query.limit(10).all()
    types = ArticleType.query.all()

    return render_template('web/index.html', articles=articles, types=types, user=user)


@web_blue.route('/article/')
def article():
    user_id = session['user_id']
    user = User.query.get(user_id)
    articles = Article.query.all()
    types = ArticleType.query.all()
    count_type = []
    for art in articles:
        count_type.append(art.type)
    return render_template('web/article.html', articles=articles, types=types, count_type=count_type)


@web_blue.route('/a_type/<int:id>/')
def a_type(id):
    articles = Article.query.filter(id == Article.type).all()
    print(articles)
    type = ArticleType.query.get(id)
    return render_template('web/a_type.html', type=type, articles=articles)


@web_blue.route('/message/')
def message():
    articles = Article.query.all()
    return render_template('web/message.html', articles=articles)


@web_blue.route('/read/<int:id>/')
def read(id):
    article = Article.query.get(id)
    user_id = session['user_id']
    user = User.query.get(user_id)
    return render_template('web/read.html', article=article, user=user)


@web_blue.route('/about/')
def about():
    articles = Article.query.all()
    return render_template('web/about.html', articles=articles)

blog/templates/web/a_type.html
{% extends 'web/base_main.html' %}

{% block css %}
	{{ super() }}
    <link rel="stylesheet" href="/static/web/css/blog.css" />
{% endblock %}

{% block js %}
	{{ super() }}
 	<script src="/static/web/js/yss/article.js"></script>
{% endblock %}

{% block title %}
	分类--{{ type.t_name }}
{% endblock %}

{% block content %}
    <div class="doc-container" id="doc-container">
        <div class="container-fixed">
		    <div class="col-content">
		        <div class="inner">
		            <article class="article-list bloglist" id="LAY_bloglist" >
						{% for article in articles %}
						<section class="article-item zoomIn article">
							<div class="fc-flag">置顶</div>
							<h5 class="title">
								<span class="fc-blue">【原创】</span>
								<a href="{{ url_for('web.read', id=article.id) }}">{{ article.title }}</a>
							</h5>
							<div class="time">
								<span class="day">{{ article.create_time.day }}</span>
								<span class="month fs-18">{{ article.create_time.month }}<span class="fs-14">月</span></span>
								<span class="year fs-18 ml10">{{ article.create_time.year }}</span>
							</div>
							<div class="content">
								<a href="read.html" class="cover img-light">
									<img src="/static/web/image/2018415193031394.jpg">
								</a>
								{{ article.desc }}
							</div>
							<div class="read-more">
								<a href="{{ url_for('web.read', id=article.id) }}" class="fc-black f-fwb">继续阅读</a>
							</div>
							<aside class="f-oh footer">
								<div class="f-fl tags">
									<span class="fa fa-tags fs-16"></span>
									<a class="tag">{{ article.tp.t_name }}</a>
								</div>
								<div class="f-fr">
									<span class="read">
										<i class="fa fa-eye fs-16"></i>
										<i class="num">0</i>
									</span>
									<span class="ml20">
										<i class="fa fa-comments fs-16"></i>
										<a href="javascript:void(0)" class="num fc-grey">0</a>
									</span>
								</div>
							</aside>
						</section>
						{% endfor %}
		            </article>
		        </div>
		    </div>
		</div>
    </div>
{% endblock %}

blog/templates/web/about.html
{% extends 'web/base_main.html' %}

{% block title %}
    关于我
{% endblock %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="/static/web/css/about.css" />
{% endblock %}

{% block js %}
    {{ super() }}
    <script src="/static/web/js/plugins/blogbenoitboucart.min.js"></script>
{% endblock %}




{% block content %}
    <div class="doc-container" id="doc-container">
        <div class="about-banner" id="container">
		    <header class="l-top hasAnim arrow-holder">
		        <a data-path-hover="M31.3184948,33.1943359 C36.3357454,28.0664371 44.4728686,28.0690462 49.572124,33.2807584 C54.6360745,38.4563871 54.6061839,46.8782889 49.6566817,51.9369454 L31.318494,69.5197703 L49.6566817,89.71735 C54.6739322,94.8452488 54.6713794,103.161825 49.572124,108.373537 C44.5081735,113.549166 36.267997,113.518616 31.3184948,108.459959 L3.8112137,78.891075 C-1.25273677,73.7154463 -1.2880417,65.3601778 3.8112137,60.1484655 L31.3184948,33.1943359 Z">
		            <svg width="0" height="0">
		                <path fill="#fff" d="M58.9103319,3.8342148C63.9275825,-1.29368407,72.0647057,-1.29107495,77.1639611,3.92063726C82.2279116,9.09626594,82.198021,17.5181678,77.2485188,22.5768242C77.2485188,22.5768242,31.318494,69.5197703,31.318494,69.5197703C31.318494,69.5197703,77.2485188,116.462716,77.2485188,116.462716C82.2657693,121.590615,82.2632165,129.907191,77.1639611,135.118903C72.1000106,140.294532,63.8598341,140.263982,58.9103319,135.205326C58.9103319,135.205326,3.8112137,78.891075,3.8112137,78.891075C-1.25273677,73.7154463,-1.2880417,65.3601778,3.8112137,60.1484655C3.8112137,60.1484655,58.9103319,3.8342148,58.9103319,3.8342148C58.9103319,3.8342148,58.9103319,3.8342148,58.9103319,3.8342148"></path>
		            </svg>
		        </a>
		        <a data-path-hover="M31.3184948,33.1943359 C36.3357454,28.0664371 44.4728686,28.0690462 49.572124,33.2807584 C54.6360745,38.4563871 54.6061839,46.8782889 49.6566817,51.9369454 L31.318494,69.5197703 L49.6566817,89.71735 C54.6739322,94.8452488 54.6713794,103.161825 49.572124,108.373537 C44.5081735,113.549166 36.267997,113.518616 31.3184948,108.459959 L3.8112137,78.891075 C-1.25273677,73.7154463 -1.2880417,65.3601778 3.8112137,60.1484655 L31.3184948,33.1943359 Z">
		            <svg width="0" height="0">
		                <path fill="#fff" d="M58.9103319,3.8342148 C63.9275825,-1.29368407 72.0647057,-1.29107495 77.1639611,3.92063726 C82.2279116,9.09626594 82.198021,17.5181678 77.2485188,22.5768242 L31.318494,69.5197703 L77.2485188,116.462716 C82.2657693,121.590615 82.2632165,129.907191 77.1639611,135.118903 C72.1000106,140.294532 63.8598341,140.263982 58.9103319,135.205326 L3.8112137,78.891075 C-1.25273677,73.7154463 -1.2880417,65.3601778 3.8112137,60.1484655 L58.9103319,3.8342148 Z"></path>
		            </svg>
		        </a>
		    </header>
		    <div class="about-title">
		        <h1>关于我</h1>
		        <p>奋斗没有终点，任何时候都是一个起点。</p>
		    </div>
		</div>
		<div class="container-fixed">
		    <div class="container-inner">
		        <article>
		            <section>
		                <h1>关于博主</h1>
		                <p>
		                    <i class="fa fa-close"></i>Python&nbsp;
		                    <i class="fa fa-close"></i>动漫迷&nbsp;
		                    <i class="fa fa-close"></i>英雄联盟&nbsp;
		                    <i class="fa fa-close"></i>小说&nbsp;
		                </p>
                        <img src="/static/web/image/tx.jpg" alt="" style="width=100px;height:100px; margin-left: 20px; border-radius:50px">
		                <p>
		                    一个处于即将毕业阶段的大四学生，学的是计算机编程,，目前在学Python。
		                </p>
		            </section>
		        </article>
		    </div>
		</div>
    </div>

{% endblock %}

blog/templates/web/article.html
{% extends 'web/base_main.html' %}

{% block css %}
	{{ super() }}
    <link rel="stylesheet" href="/static/web/css/blog.css" />
{% endblock %}

{% block js %}
	{{ super() }}
 	<script src="/static/web/js/yss/article.js"></script>
{% endblock %}

{% block title %}
	文章
{% endblock %}

{% block content %}
    <div class="doc-container" id="doc-container">
        <div class="container-fixed">
		    <div class="col-content">
		        <div class="inner">
		            <article class="article-list bloglist" id="LAY_bloglist" >
						{% for article in articles %}
						<section class="article-item zoomIn article">
							<div class="fc-flag">置顶</div>
							<h5 class="title">
								<span class="fc-blue">【原创】</span>
								<a href="{{ url_for('web.read', id=article.id) }}">{{ article.title }}</a>
							</h5>
							<div class="time">
								<span class="day">{{ article.create_time.day }}</span>
								<span class="month fs-18">{{ article.create_time.month }}<span class="fs-14">月</span></span>
								<span class="year fs-18 ml10">{{ article.create_time.year }}</span>
							</div>
							<div class="content">
								<a href="read.html" class="cover img-light">
									<img src="/static/web/image/2018415193031394.jpg">
								</a>
								{{ article.desc }}
							</div>
							<div class="read-more">
								<a href="{{ url_for('web.read', id=article.id) }}" class="fc-black f-fwb">继续阅读</a>
							</div>
							<aside class="f-oh footer">
								<div class="f-fl tags">
									<span class="fa fa-tags fs-16"></span>
									<a class="tag">{{ article.tp.t_name }}</a>
								</div>
								<div class="f-fr">
									<span class="read">
										<i class="fa fa-eye fs-16"></i>
										<i class="num">0</i>
									</span>
									<span class="ml20">
										<i class="fa fa-comments fs-16"></i>
										<a href="javascript:void(0)" class="num fc-grey">0</a>
									</span>
								</div>
							</aside>
						</section>
						{% endfor %}
		            </article>
		        </div>
		    </div>
		    <div class="col-other">
		        <div class="inner">
					<div class="other-item" id="categoryandsearch">
			    		<div class="search">
					        <label class="search-wrap">
					            <input type="text" id="searchtxt" placeholder="输入关键字搜索" />
					            <span class="search-icon">
					                <i class="fa fa-search"></i>
					            </span>
					        </label>
			        		<ul class="search-result"></ul>
			    		</div>
			    		<ul class="category mt20" id="category">
				        	<li data-index="0" class="slider"></li>
				        	<li data-index="1"><a href="#">全部分类</a></li>

							{% for type in types %}
				            <li data-index="0"><a href="{{ url_for('web.a_type', id=type.id) }}">{{ type.t_name }}【{{ count_type.count(type.id) }}】</a></li>
							{% endfor %}
			    		</ul>
					</div>
					<!--右边悬浮 平板或手机设备显示-->
					<div class="category-toggle"><i class="layui-icon">&#xe603;</i></div>
					<div class="article-category">
					    <div class="article-category-title">分类导航</div>
					            {% for type in types %}
					            <a href="#">type.t_name</a>
								{% endfor %}
					    <div class="f-cb"></div>
					</div>
					<!--遮罩-->
					<div class="blog-mask animated layui-hide"></div>
					<div class="other-item">
					    <h5 class="other-item-title">最新文章</h5>
					    <div class="inner">
					        <ul class="hot-list-article">
					                {% for article in articles %}
					                	<li> <a href="{{ url_for('web.read', id=article.id) }}">{{ article.title }}</a></li>
									{% endfor %}
					        </ul>
					    </div>
					</div>

		        </div>
		    </div>
		</div>
    </div>
{% endblock %}

blog/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
        {% block css %}
        {% endblock %}

        {% block js %}
        {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}
</body>
</html>

blog/templates/web/base_main.html
{% extends 'web/base.html' %}


{% block css %}
    <link rel="stylesheet" href="/static/web/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/static/web/layui/css/layui.css" />
    <link rel="stylesheet" href="/static/web/css/master.css" />
    <link rel="stylesheet" href="/static/web/css/gloable.css" />
    <link rel="stylesheet" href="/static/web/css/nprogress.css" />
{% endblock %}

{% block js %}
    <script src="/static/web/layui/layui.js"></script>
    <script src="/static/web/js/yss/gloable.js"></script>
    <script src="/static/web/js/plugins/nprogress.js"></script>
    <script>NProgress.start();</script>
    <script>
        window.onload = function () {
            NProgress.done();
        };
    </script>
{% endblock %}

{% block header %}
<div class="header">
    </div>
    <header class="gird-header">
        <div class="header-fixed">
            <div class="header-inner">
                <a href="javascript:void(0)" class="header-logo" id="logo">Lin</a>
                <nav class="nav" id="nav">
                    <ul>
                        <li><a href="{{ url_for('web.index') }}">首页</a></li>
                        <li><a href="{{ url_for('web.article') }}">博客</a></li>
                        <li><a href="{{ url_for('web.message') }}">留言</a></li>
                        <li><a href="{{ url_for('web.about') }}">关于我</a></li>
                    </ul>
                </nav>
                <a href="{{ url_for('back.login') }}" class="blog-user">
                    <i class="fa fa-qq">后台管理</i>
                </a>
                <a class="phone-menu">
                    <i></i>
                    <i></i>
                    <i></i>
                </a>
            </div>
        </div>
    </header>
{% endblock %}

{% block footer %}
    <footer class="grid-footer">
        <div class="footer-fixed">
            <div class="copyright">
                <div class="info">
                    <div class="contact">
                        <a href="https://github.com/CCWAY/blog" class="github" target="_blank"><i class="fa fa-github"></i></a>
                        <a href="https://wpa.qq.com/msgrd?v=3&uin=1049482756&site=qq&menu=yes" class="qq" target="_blank" title="1049482756"><i class="fa fa-qq"></i></a>
                        <a href="https://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=1049482756@qq.com" class="email" target="_blank" title="1049482756@qq.com"><i class="fa fa-envelope"></i></a>
                        <a href="javascript:void(0)" class="weixin"><i class="fa fa-weixin"></i></a>
                    </div>
                    <p class="mt05">
                        Copyright &copy; 2018-2018 林、Lin All Rights Reserved V.1.0.0 渝ICP备18008600号
                    </p>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}

blog/templates/web/index.html
<!DOCTYPE html>
<html lang="zh-Hans-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width" />
    <title>林、Lin的个人博客</title>
    <link href="/static/web/layui/css/layui.css" rel="stylesheet" type="text/css">
    <link href="/static/web/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/static/web/css/index_style.css" rel="stylesheet" type="text/css">
    <link href="/static/web/css/animate.min.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div id="menu" class="hover_animation menu_open" data-mark="false">
        <span></span>
        <span></span>
        <span></span>
    </div>
    <div id="navgation" class="navgation navgation_close">
        <ul class="point">
            <li><a href="#">首页</a></li>
            <li><a href="{{ url_for('web.article') }}">博客</a></li>
            <li><a href="{{ url_for('web.message') }}">留言</a></li>
        </ul>
        <div class="logo"><a>{{ user.username }}</a></div>
    </div>
    <div class="section" id="section1">
        <div class="fp-tablecell">
            <div class="page1">
                <div class="nav wow zoomIn" data-wow-duration="2s">
                    <h1>林、Lin</h1>
                    <p>计算机善于遵循指令，但不善于理解你的思维</p>
                    <a class="layui-btn layui-btn-normal" style="margin-top: 20px" href="{{ url_for('web.article') }}">进入博客</a>
                </div>
                <a class="next wow fadeInUp" data-wow-duration="2s" id="next"></a>
            </div>
        </div>
    </div>
    <div class="section" id="section2">
        <div class="fp-tablecell">
            <div class="page2">
                <div class="warp-box">
                    <div class="new-article">
                        <div class="inner wow fadeInDown" data-wow-delay=".2s">
                            <h1>热门文章</h1>
                            <p>
                                很想给你写封信,告诉你这里的天气.
                                <br>昨夜的那场电影,还有我的心情.
                            </p>
                        </div>
                    </div>
                    <div class="layui-row">
                        {% for article in articles %}
                        <div class="layui-col-xs12 layui-col-sm4 layui-col-md4  wow fadeInUp" style="padding: 0 10px">
                            <div class="single-news">
                                <div class="news-head">
                                    <img src="/static/web/image/1.jpg">
                                    <a href="{{ url_for('web.read', id=article.id) }}" class="link"><i class="fa fa-link"></i></a>
                                </div>
                                <div class="news-content">
                                    <h4>
                                        <a href="{{ url_for('web.read', id=article.id) }}">
                                            {{ article.title }}
                                        </a>
                                    </h4>
                                    <div class="date">
                                        {{ article.create_time }}
                                    </div>
                                    <p>
                                        {{ article.desc }}
                                    </p>
                                    <a href="{{ url_for('web.read', id=article.id) }}" class="btn">
                                        阅读更多 
                                    </a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="section" id="section3">
        <div class="fp-tablecell">
            <div class="page3">
                <div class="warp-box">
                    <div class="warp">
                        <div class="inner">
                            <div class="links">
                                <ul>
                                    <li class="wow fadeInLeft"><a href="{{ url_for('web.about') }}">关于</a></li>
                                    <li class="wow fadeInRight"><a href="#">+友情链接</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="section" id="section4">
        <div class="fp-tablecell">
            <div class="page4">
                <div class="warp-box">
                    <div class="about">
                        <div class="inner">
                            <h1 class="wow fadeInLeft">兴趣爱好</h1>
                            <p class="wow fadeInRight">
                                爱好游戏，动漫。闲来无事喜欢在一些不健康的场所虚度光阴。
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer wow fadeInUp" id="contact">
        <div class="footer-top">
            <div class="container">
                <div class="layui-row">
                    <div class="layui-col-xs12 layui-col-sm6 layui-col-md4">
                        <div class="single-widget about">
                            <div class="footer-logo">
                                <h2>林、Lin</h2>
                            </div>
                            <p>人生苦短，我用Python</p>
                            <div class="button">
                                <a href="{{ url_for('web.about') }}" class="btn layui-btn layui-btn-normal">About Me</a>
                            </div>
                        </div>
                    </div>
                    <div class="layui-col-xs12 layui-col-sm6 layui-col-md4">
                        <div class="single-widget">
                            <h2>相关链接</h2>
                            <ul class="social-icon">
                                <li class="active"><a href="#"><i class="fa fa-book"></i>博文</a></li>
                                <li class="active"><a href="#"><i class="fa fa-comments"></i>留言</a></li>
                                <li class="active"><a href="#"><i class="fa fa-share"></i>资源</a></li>
                                <li class="active"><a href="#"><i class="fa fa-snowflake-o"></i>日记</a></li>
                                <li class="active"><a href="#"><i class="fa fa-files-o"></i>归档</a></li>
                            </ul>                   
                        </div>
                    </div>
                    <div class="layui-col-xs12 layui-col-sm12 layui-col-md4">
                        <div class="single-widget contact">
                            <h2>联系我</h2>
                            <ul class="list">
                                <li><i class="fa fa-map"></i>地址: 中国重庆市</li>
                                <li><i class="fa fa-qq"></i>QQ: 1049482756 </li>
                                <li><i class="fa fa-envelope"></i>邮箱: 1049482456@qq.com</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright">
            <div class="container">
                <div class="layui-row">
                    <div class="layui-col-xs12 layui-col-sm12 layui-col-md12 text-center">
                        <p>Copyright &copy; 2018-2018 林、Lin All Rights Reserved V.3.1.3 渝ICP备18008600号</p>
                    </div>
                </div>
            </div>
        </div>  
    </footer>
    <script src="/static/web/layui/layui.js"></script>
    <script src="/static/web/js/wow.min.js"></script>
    <script src="/static/web/js/index.js"></script>
</body>
</html>

blog/templates/web/message.html
{% extends 'web/base_main.html' %}

{% block title %}
    留言板
{% endblock %}

{% block css %}
    {{ super() }}
    <link rel="stylesheet" href="/static/web/css/message.css" />
{% endblock %}

{% block js %}
    {{ super() }}
    <script src="/static/web/js/pagemessage.js"></script>
{% endblock %}


{% block content %}
    <div class="doc-container" id="doc-container">
        <div class="container-fixed">
    <div class="container-inner">
        <section class="msg-remark">
            <h1>留言板</h1>
            <p>
                沟通交流，拉近你我！
            </p>
        </section>
        <div class="textarea-wrap message" id="textarea-wrap">
            <form class="layui-form blog-editor" action="">
                <div class="layui-form-item">
                    <textarea name="editorContent" lay-verify="content" id="remarkEditor" placeholder="请输入内容" class="layui-textarea layui-hide"></textarea>
                </div>
                <div class="layui-form-item">
                    <button class="layui-btn" lay-submit="formLeaveMessage" lay-filter="formLeaveMessage">提交留言</button>
                </div>
            </form>
        </div>
    </div>
    <div class="f-cb"></div>
    <div class="mt20">
        <ul class="message-list" id="message-list">
            <li class="zoomIn article">
                <div class="comment-parent">
                    <a name="remark-1"></a>
                    <img src="/static/web/image/tx.jpg"  />
                    <div class="info">
                        <span class="username">我</span>
                    </div>
                    <div class="comment-content">
                        功能还在路上
                    </div>
                    <p class="info info-footer">
                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                        <span>重庆</span>
                        <span class="comment-time">2018-01-01</span>
                        <a href="javascript:;" class="btn-reply" data-targetid="1" data-targetname="燕十三">回复</a>
                    </p>
                </div>
                <hr />

            <li class="zoomIn article"> 
                <div class="comment-parent">
                    <a name="remark-1"></a>
                    <img src="https://thirdqq.qlogo.cn/qqapp/101465933/7627F745B95BFAC18C6C481FE72B4EB1/100" alt="{{name}}" />
                    <div class="info">
                        <span class="username">用户1</span>
                    </div>
                    <div class="comment-content">
                        等待
                    </div>
                    <p class="info info-footer">
                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                        <span>四川</span>
                        <span class="comment-time">2018-01-01</span>
                        <a href="javascript:;" class="btn-reply" data-targetid="1" data-targetname="燕十三">回复</a>
                    </p>
                </div>
                <div class="replycontainer layui-hide"> 
                    <form class="layui-form" action=""> 
                        <input type="hidden" name="remarkId" value="1"> 
                        <input type="hidden" name="targetUserId" value="0"> 
                        <div class="layui-form-item"> 
                            <textarea name="replyContent" lay-verify="replyContent" placeholder="请输入回复内容" class="layui-textarea" style="min-height:80px;"></textarea> 
                        </div> 
                        <div class="layui-form-item"> 
                            <button class="layui-btn layui-btn-xs" lay-submit="formReply" lay-filter="formReply">提交</button> 
                        </div> 
                    </form> 
                </div>
            </li>
            <li class="zoomIn article"> 
                <div class="comment-parent">
                    <a name="remark-1"></a>
                    <img src="https://thirdqq.qlogo.cn/qqapp/101465933/7627F745B95BFAC18C6C481FE72B4EB1/100"/>
                    <div class="info">
                        <span class="username">燕十三</span>
                    </div>
                    <div class="comment-content">
                        剑气纵横三万里
                    </div>
                    <p class="info info-footer">
                        <i class="fa fa-map-marker" aria-hidden="true"></i>
                        <span>四川</span> 
                        <span class="comment-time">2018-01-01</span>
                        <a href="javascript:;" class="btn-reply" data-targetid="1" data-targetname="燕十三">回复</a>
                    </p>
                </div>
                <hr />
                <div class="replycontainer layui-hide"> 
                    <form class="layui-form" action=""> 
                        <input type="hidden" name="remarkId" value="1"> 
                        <input type="hidden" name="targetUserId" value="0"> 
                        <div class="layui-form-item"> 
                            <textarea name="replyContent" lay-verify="replyContent" placeholder="请输入回复内容" class="layui-textarea" style="min-height:80px;"></textarea> 
                        </div> 
                        <div class="layui-form-item"> 
                            <button class="layui-btn layui-btn-xs" lay-submit="formReply" lay-filter="formReply">提交</button> 
                        </div> 
                    </form> 
                </div>
            </li>
        </ul>
    </div>
</div>
    </div>
{% endblock %}