blog/back/models.py
from datetime import datetime

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(10), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    is_delete = db.Column(db.Boolean, default=0)
    create_time = db.Column(db.DateTime, default=datetime.now)

    __tablename__ = 'user'

    def save(self):
        db.session.add(self)
        db.session.commit()


class ArticleType(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    t_name = db.Column(db.String(10), unique=True, nullable=False)
    arts = db.relationship('Article', backref='tp')

    __tablename__ = 'art_type'


class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(30), unique=True, nullable=False)
    desc = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    type = db.Column(db.Integer, db.ForeignKey('art_type.id'))

blog/back/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from werkzeug.security import generate_password_hash, check_password_hash
from back.models import User, ArticleType, db, Article
from utils.functions import is_login

back_blue = Blueprint('back', __name__)


@back_blue.route('/index/')
@is_login
def index():

    return render_template('back/index.html')


@back_blue.route('/register/', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('back/register.html')
    if request.method == 'POST':
        # 获取数据
        username = request.form.get('username')
        password = request.form.get('password')
        password2 = request.form.get('password2')
        if username and password and password2:
            # 先判断该账号是否被注册过
            user = User.query.filter(User.username == username).first()
            if user:
                # 判断该账号已经被注册过
                error = '该账号已经被注册过, 请更换账号'
                return render_template('back/register.html', error=error)
            else:
                if password2 == password:
                    # 保存数据
                    user = User()
                    user.username = username
                    user.password = generate_password_hash(password)
                    user.save()
                    return redirect(url_for('back.login'))
                else:
                    # 密码错误
                    error = '两次密码不一致'
                    return render_template('back/register.html', error=error)
        else:
            error = '请填写完整的信息'
            return render_template('back/register.html', error=error)


@back_blue.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('back/login.html')

    if request.method == 'POST':
        # 获取数据
        username = request.form.get('username')
        password = request.form.get('password')
        if username and password:
            user = User.query.filter(User.username == username).first()
            if not user:
                error = '该账号不存在，请注册'
                return render_template('back/login.html', error=error)
            if not check_password_hash(user.password, password):
                error = '你的密码有误'
                return render_template('back/login.html', error=error)
            # 账号和密码匹配正确，跳转到首页
            session['user_id'] = user.id
            return redirect(url_for('back.index'))

        else:
            error = '请填写完整信息'
            return render_template('back/login.html', error=error)


@back_blue.route('/logout/', methods=['GET'])
@is_login
def logout():
    del session['user_id']
    return redirect(url_for('back.login'))


@back_blue.route('/a_type/', methods=['GET', 'POST'])
def a_type():
    if request.method == 'GET':
        types = ArticleType.query.all()
        return render_template('back/category_list.html', types=types)


@back_blue.route('/add_type/', methods=['GET', 'POST'])
def add_type():
    if request.method == 'GET':
        return render_template('back/category_add.html')

    if request.method == 'POST':
        atype = request.form.get('atype')
        if atype:
            # 保存分类信息
            art_type = ArticleType()
            art_type.t_name = atype
            db.session.add(art_type)
            db.session.commit()
            return redirect(url_for('back.a_type'))
        else:
            error = '请填写分类信息'
            return render_template('back/category_add.html', error=error)


@back_blue.route('/del_type/<int:id>/', methods=['GET'])
def del_type(id):
    # 删除分类
    atype = ArticleType.query.get(id)
    db.session.delete(atype)
    db.session.commit()
    return redirect(url_for('back.a_type'))


@back_blue.route('/article_list/', methods=['GET'])
def article_list():
    articles = Article.query.all()
    return render_template('back/article_list.html', articles=articles)


@back_blue.route('/article_add/', methods=['GET', 'POST'])
def article_add():
    if request.method == 'GET':
        types = ArticleType.query.all()
        return render_template('back/article_detail.html', types=types)
    if request.method == 'POST':
        title = request.form.get('name')
        desc = request.form.get('desc')
        category = request.form.get('category')
        content = request.form.get('content')
        if title and desc and category and content:
            # 保存
            art = Article()
            art.title = title
            art.desc = desc
            art.content = content
            art.type = category
            db.session.add(art)
            db.session.commit()
            return redirect(url_for('back.article_list'))

        else:
            error = '请填写完整的文章信息'
            return render_template('back/article_detail.html', error=error)


@back_blue.route('/del_art/<int:id>', methods=['GET'])
def del_art(id):
    # 删除文章
    art = Article.query.get(id)
    db.session.delete(art)
    db.session.commit()
    return redirect(url_for('back.article_list'))


@back_blue.route('/article_update/<int:id>/', methods=['GET', 'POST'])
def article_update(id):

    if request.method == 'GET':
        art1 = Article.query.get(id)
        name = art1.title
        desc = art1.desc
        content = art1.content
        types = ArticleType.query.all()
        return render_template('back/article_update.html', types=types, name=name, desc=desc, content=content, art1=art1)
    if request.method == 'POST':
        title = request.form.get('name')
        desc = request.form.get('desc')
        category = request.form.get('category')
        content = request.form.get('content')
        if title and desc and category and content:
            # 保存

            art = Article.query.get(id)
            art.title = title
            art.desc = desc
            art.content = content
            art.type = category
            db.session.add(art)
            db.session.commit()
            return redirect(url_for('back.article_list'))

        else:
            error = '请填写完整的文章信息'
            return render_template('back/article_update.html', error=error)


@back_blue.route('/user_list/', methods=['GET', 'POST'])
def user_list():
    if request.method == 'GET':
        users = User.query.all()
        return render_template('back/user_list.html', users=users)


@back_blue.route('/update_pwd/', methods=['GET', 'POST'])
def update_pwd():
    id = session['user_id']
    if request.method == 'GET':
        return render_template('back/update_pwd.html')

    if request.method == 'POST':
        user = User.query.get(id)
        password = request.form.get('password')
        password2 = request.form.get('password2')
        if password and password2:
            if not check_password_hash(user.password, password):
                error = '旧密码输入有误'
                return render_template('back/update_pwd.html', error=error)
            if password == password2:
                error = '旧密码不能和新密码相同'
                return render_template('back/update_pwd.html', error=error)
            # 保存新密码
            user.password = generate_password_hash(password2)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('back.user_list'))
        else:
            error = '密码不能为空!'
            return render_template('back/update_pwd.html', error=error)

blog/web/views.py
from flask import Blueprint, render_template, session

from back.models import Article, User, ArticleType

web_blue = Blueprint('web', __name__)


@web_blue.route('/index/')
def index():
    user_id = session['user_id']
    user = User.query.get(user_id)
    articles = Article.query.limit(10).all()
    types = ArticleType.query.all()

    return render_template('web/index.html', articles=articles, types=types, user=user)


@web_blue.route('/article/')
def article():
    user_id = session['user_id']
    user = User.query.get(user_id)
    articles = Article.query.all()
    types = ArticleType.query.all()
    count_type = []
    for art in articles:
        count_type.append(art.type)
    return render_template('web/article.html', articles=articles, types=types, count_type=count_type)


@web_blue.route('/a_type/<int:id>/')
def a_type(id):
    articles = Article.query.filter(id == Article.type).all()
    print(articles)
    type = ArticleType.query.get(id)
    return render_template('web/a_type.html', type=type, articles=articles)


@web_blue.route('/message/')
def message():
    articles = Article.query.all()
    return render_template('web/message.html', articles=articles)


@web_blue.route('/read/<int:id>/')
def read(id):
    article = Article.query.get(id)
    user_id = session['user_id']
    user = User.query.get(user_id)
    return render_template('web/read.html', article=article, user=user)


@web_blue.route('/about/')
def about():
    articles = Article.query.all()
    return render_template('web/about.html', articles=articles)

blog/templates/back/article_detail.html
{% extends 'back/base_main.html' %}

{% block title %}
    添加文章
{% endblock %}


{% block js %}
    {{ super() }}
{% endblock %}

{% block content %}
<section class="rt_wrap mCustomScrollbar">

    <div class="rt_content">
        <div class="page_title">
            <a class="fr top_rt_btn" href="{{ url_for('back.article_list') }}">返回文章列表</a>
        </div>
        <form action="" method="post">
            {{ error }}
            <input type='hidden' name='csrfmiddlewaretoken' value='q3tTrBuDcMhfvSS9x2u0yQAyRbboSQuyMyt42kgwgKS0rKxCv31hIWTsS3ULhZn7' />
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">文章标题：</span>
                        <input type="text" name="name" value="" class="textbox textbox_295" placeholder="文章标题..."/>
                        
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">文章描述：</span>
                        <input type="text" name="desc" value=""  class="textbox" placeholder="文章描述..."/>
                        
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">分类：</span>
                        <select class="select" name="category">
                            {% for type in types %}
                                <option value="{{ type.id }}">{{ type.t_name }}</option>
                            {% endfor %}

                        </select>

                    </li>
                    <li>
                    </li>

                    <li>
                        <span class="item_name" style="width:120px;">文章详情：</span>

                            <textarea id="editor" name="content" style="width:100%; height:200px;"></textarea>

                            <link rel="stylesheet" type="text/css" href="/static/wangEditor/dist/css/wangEditor.min.css">

                            <script type="text/javascript" src="/static/wangEditor/dist/js/lib/jquery-1.10.2.min.js"></script>
                            <script type="text/javascript" src="/static/wangEditor/dist/js/wangEditor.min.js"></script>
                            <script type="text/javascript">
                                    $(function () {
                                        var editor = new wangEditor('editor');
                                        editor.create();
                                    });
                                </script>
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>
{% endblock %}

blog/templates/back/article_list.html
{% extends 'back/base_main.html' %}

{% block title %}
    文章列表页面
{% endblock %}


{% block content %}

<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">文章列表</h2>
            <a href="{{ url_for('back.article_add') }}" class="fr top_rt_btn add_icon">添加文章</a>
        </div>
        <table class="table">
            <tr>
                <th>文章标题</th>
                <th>文章分类</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
            {% for article in articles %}
                <tr>
                    <td class="center">{{ article.title }}</td>
                    <td class="center">{{ article.tp.t_name }}</td>
                    <td class="center">
                        {{ article.create_time }}
                    </td>
                    <td class="center">
                        <a href="{{ url_for('back.article_update', id=article.id) }}" title="编辑" class="link_icon">&#101;</a>
                        <a href="{{ url_for('back.del_art', id=article.id) }}" onclick="" title="删除" class="link_icon">&#100;</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <aside class="paging">
            <a>当前1页</a>
            <a href="">第一页</a>
            
                <a href=""> 1 </a>
            
                <a href=""> 2 </a>
            
                <a href=""> 3 </a>
            
            <a href="">最后一页</a>
        </aside>
    </div>
</section>


{% endblock %}

blog/templates/back/article_update.html
{% extends 'back/base_main.html' %}

{% block title %}
    修改文章
{% endblock %}


{% block js %}
    {{ super() }}
    <script type="text/javascript" src="/static/kindeditor/kindeditor-all.js"></script>
    <script type="text/javascript" src="/static/kindeditor/lang/zh-CN.js"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id');
        });
    </script>
{% endblock %}

{% block content %}
<section class="rt_wrap mCustomScrollbar">

    <div class="rt_content">
        <div class="page_title">
            <a class="fr top_rt_btn" href="{{ url_for('back.article_list') }}">返回文章列表</a>
        </div>
        <form action="" method="post">
            {{ error }}
            <input type='hidden' name='csrfmiddlewaretoken' value='q3tTrBuDcMhfvSS9x2u0yQAyRbboSQuyMyt42kgwgKS0rKxCv31hIWTsS3ULhZn7' />
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">文章标题：</span>
                        <input type="text" name="name" value=" {{ name }} " class="textbox textbox_295" placeholder="文章标题..."/>
                        
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">文章描述：</span>
                        <input type="text" name="desc" value="{{ desc }}"  class="textbox" placeholder="文章描述..."/>
                        
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">分类：</span>
                        <select class="select" name="category">
                            {% for type in types %}
                                {% if type.id == art1.type %}
                                    <option value="{{ type.id }}" selected="selected">{{ type.t_name }}</option>
                                {% else %}
                                    <option value="{{ type.id }}">{{ type.t_name }}</option>
                                {% endif %}
                            {% endfor %}

                        </select>

                    </li>
                    <li>
                    </li>

                    <li>
                        <span class="item_name" style="width:120px;">文章详情：</span>

                        <textarea id="editor" name="content" style="width:100%; height:200px;">
                            {{ content }}
                        </textarea>

                            <link rel="stylesheet" type="text/css" href="/static/wangEditor/dist/css/wangEditor.min.css">
                            <script type="text/javascript" src="/static/wangEditor/dist/js/lib/jquery-1.10.2.min.js"></script>
                            <script type="text/javascript" src="/static/wangEditor/dist/js/wangEditor.min.js"></script>
                            <script type="text/javascript">
                                    $(function () {
                                        var editor = new wangEditor('editor');
                                        editor.create();
                                    });
                                </script>
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>
{% endblock %}

blog/templates/back/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
        {% block css %}
        {% endblock %}

        {% block js %}
        {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}

    {% block aside %}
    {% endblock %}

    {% block content %}
    {% endblock %}
</body>
</html>

blog/templates/back/base_main.html
{% extends 'back/base.html' %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="/static/back/css/style.css">
{% endblock %}

{% block js %}
    <script src="/static/back/js/jquery.js"></script>
    <script src="/static/back/js/jquery.mCustomScrollbar.concat.min.js"></script>
{% endblock %}

{% block header %}
    <header>
    <h1><img src="/static/back/images/admin_logo.png"/></h1>
    <ul class="rt_nav">
        <li><a href="{{ url_for('web.index') }}" target="_blank" class="website_icon">站点首页</a></li>
        <li><a href="{{ url_for('back.update_pwd') }}" class="set_icon">账号设置</a></li>
        <li><a href="{{ url_for('back.logout') }}" class="quit_icon">安全退出</a></li>
    </ul>
</header>
{% endblock %}

{% block aside %}
    <aside class="lt_aside_nav content mCustomScrollbar">
    <h2><a href="">博客后台菜单栏</a></h2>
    <ul>
        <li>
            <dl>
                <dt>文章管理</dt>
                <!--当前链接则添加class:active-->
                <dd><a href="{{ url_for('back.a_type') }}">文章分类</a></dd>
                <dd><a href="{{ url_for('back.article_list') }}">文章列表</a></dd>
            </dl>
        </li>
        <li>
            <dl>
                <dt>用户管理</dt>
                <dd><a href="{{ url_for('back.user_list') }}">用户信息</a></dd>
            </dl>
        </li>
    </ul>
</aside>
{% endblock %}

blog/templates/back/category_add.html
{% extends 'back/base_main.html' %}

{% block title %}
    添加分类
{% endblock %}

{% block content %}

<section class="rt_wrap mCustomScrollbar">

    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">文章分类详情</h2>
            <a class="fr top_rt_btn" href="{{ url_for('back.a_type') }}">返回文章分类列表</a>
        </div>
        <form action="" method="post">
            {{ error }}
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">分类名称：</span>
                        <input type="text" name="atype">
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>

{% endblock %}

blog/templates/back/category_list.html
{% extends 'back/base_main.html' %}

{% block title %}
    文章分类
{% endblock %}

{% block content %}

<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">文章分类列表</h2>
            <a href="{{ url_for('back.add_type') }}" class="fr top_rt_btn add_icon">添加文章分类</a>
        </div>
        <table class="table">
            <tr>
                <th>分类名</th>
                <th>操作</th>
            </tr>
            {% for type in types %}
                <tr>
                    <td class="center">
                        {{ type.t_name }}
                    </td>
                    <td class="center">
                        <a href="{{ url_for('back.del_type', id=type.id) }}" title="删除" class="link_icon">&#101;</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
</section>

{% endblock %}

blog/templates/back/goods_desc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>

    </title>
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <script src="js/jquery.js"></script>
    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>

    
    <script type="text/javascript" src="/static/kindeditor/kindeditor-all.js"></script>
    <script type="text/javascript" src="/static/kindeditor/lang/zh-CN.js"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id',{
                    uploadJson:'/util/upload/kindeditor'
                });
        });
    </script>

</head>
<body>


<header>
    <h1><img src="images/admin_logo.png"/></h1>
    <ul class="rt_nav">
        <li><a href="/" target="_blank" class="website_icon">站点首页</a></li>
        <li><a href="#" class="set_icon">账号设置</a></li>
        <li><a href="login.html" class="quit_icon">安全退出</a></li>
    </ul>
</header>




    <aside class="lt_aside_nav content mCustomScrollbar">
        <h2><a href="">商城后台菜单栏</a></h2>
         <ul>
            <li>
                <dl>
                    <dt>商品管理</dt>
                    <!--当前链接则添加class:active-->
                    <dd><a href="goods_category_list.html">商品分类</a></dd>
                    <dd><a href="goods_list.html">商品列表</a></dd>
                </dl>
            </li>
            <li>
                <dl>
                    <dt>订单管理</dt>
                    <dd><a href="order_list.html">订单列表</a></dd>
                </dl>
            </li>
            <li>    
                <dl>
                    <dt>用户管理</dt>
                    <dd><a href="user_list.html">用户列表</a></dd>
                </dl>
            </li>
            </ul>
    </aside>

    <style>
    .dataStatistic{width:400px;height:200px;border:1px solid #ccc;margin:0 auto;margin:10px;overflow:hidden}
    #cylindrical{width:400px;height:200px;margin-top:-15px}
    #line{width:400px;height:200px;margin-top:-15px}
    #pie{width:400px;height:200px;margin-top:-15px}
    </style>



<section class="rt_wrap">

    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">商品详情</h2>
            <a class="fr top_rt_btn" href="/goods/goods_list/">返回商品列表</a>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            <input type='hidden' name='csrfmiddlewaretoken' value='QuPi2QUuEhlKchGijsQULGJKUZO6bOJacZPtDzGnIfWv89lLhtnbVM2EVRxtAXCJ' />
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">产品详情：</span>
                        <label style="display:inline-block;padding:15px;background:#f8f8f8;">
                            <textarea id="editor_id" name="content" style="width:700px;"></textarea>
                        </label>
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>



</body>
</html>

blog/templates/back/index.html
{% extends 'back/base_main.html' %}

{% block title %}
    后台管理系统--首页
{% endblock %}

{% block js %}
    {{ super() }}

    <script src="/static/back/js/html5.js"></script>


<script>

	(function($){
		$(window).load(function(){
			
			$("a[rel='load-content']").click(function(e){
				e.preventDefault();
				var url=$(this).attr("href");
				$.get(url,function(data){
					$(".content .mCSB_container").append(data); //load new content inside .mCSB_container
					//scroll-to appended content 
					$(".content").mCustomScrollbar("scrollTo","h2:last");
				});
			});
			
			$(".content").delegate("a[href='top']","click",function(e){
				e.preventDefault();
				$(".content").mCustomScrollbar("scrollTo",$(this).attr("href"));
			});
			
		});
	})(jQuery);
</script>
{% endblock %}

{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
        <div class="rt_content">
            <h1 style="color:red;font-size:20px;font-weight:bold;text-align:center;">
                博客管理后台
            </h1>
            <br>
            <p>采用flask开发，存储数据库为关系型数据库Mysql</p>
            <br>
            <p>后台集中功能为：文章发布、用户管理等模块</p>
        </div>
    </section>
{% endblock %}

blog/templates/back/login.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>后台登录</title>
<meta name="author" content="DeathGhost" />
<link rel="stylesheet" type="text/css" href="/static/back/css/style.css" />
<style>
body{height:100%;background:#16a085;overflow:hidden;}
canvas{z-index:-1;position:absolute;}
</style>
<script src="/static/back/js/jquery.js"></script>
<script src="/static/back/js/verificationNumbers.js"></script>
<script src="/static/back/js/Particleground.js"></script>
<script>
$(document).ready(function() {
  //粒子背景特效
  $('body').particleground({
    dotColor: '#5cbdaa',
    lineColor: '#5cbdaa'
  });
  //验证码
  createCode();
  //测试提交，对接程序删除即可
  $(".submit_btn").click(function(){
	  location.href="index.html";
	  });
});
</script>
</head>
<body>
<dl class="admin_login">
 <dt>
  <strong>博客后台管理系统</strong>
  <em>Management System</em>
 </dt>
 <form action="" method="post">
     {{ error }}
   <dd class="user_icon">
    <input type="text" name="username" placeholder="账号" class="login_txtbx"/>
   </dd>
   <dd class="pwd_icon">
    <input type="password" name="password" placeholder="密码" class="login_txtbx"/>
   </dd>
  <dd>
   <input type="submit" value="立即登录" class="submit_btn"/>
  </dd>
 </form>
</dl>
</body>
</html>

blog/templates/back/register.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>后台注册</title>
<meta name="author" content="DeathGhost" />
<link rel="stylesheet" type="text/css" href="/static/back/css/style.css" />
<style>
body{height:100%;background:#16a085;overflow:hidden;}
canvas{z-index:-1;position:absolute;}
</style>
<script src="/static/back/js/jquery.js"></script>
<script src="/static/back/js/verificationNumbers.js"></script>
<script src="/static/back/js/Particleground.js"></script>
<script>
$(document).ready(function() {
  //粒子背景特效
  $('body').particleground({
    dotColor: '#5cbdaa',
    lineColor: '#5cbdaa'
  });
  //验证码
  createCode();
  //测试提交，对接程序删除即可
  $(".submit_btn").click(function(){
	  location.href="index.html";
	  });
});
</script>
</head>
<body>
<dl class="admin_login">
 <dt>
  <strong>博客后台管理系统</strong>
  <em>Management System</em>
 </dt>
    <form action="", method="post">
        {{ error }}
        <dd class="user_icon">
            <input type="text" name="username" placeholder="账号" class="login_txtbx"/>
        </dd>
        <dd class="pwd_icon">
            <input type="password" name="password"  placeholder="密码" class="login_txtbx"/>
        </dd>
        <dd class="pwd_icon">
            <input type="password" name="password2" placeholder="确认密码" class="login_txtbx"/>
        </dd>
        <dd>
            <input type="submit" value="立即注册" class="submit_btn"/>
         </dd>
    </form>
</dl>
</body>
</html>

blog/templates/back/update_pwd.html
{% extends 'back/base_main.html' %}

{% block title %}
    修改密码
{% endblock %}

{% block content %}

<section class="rt_wrap mCustomScrollbar">

    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">填入新的密码</h2>
            <a class="fr top_rt_btn" href="{{ url_for('back.user_list') }}">返回文章分类列表</a>
        </div>
        <form action="" method="post">
            {{ error }}
            <section>
                <ul class="ulColumn2">
                    <li>
                        <span class="item_name" style="width:120px;">旧密码：</span>
                        <input type="text" name="password">
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;">新的密码：</span>
                        <input type="text" name="password2">
                    </li>
                    <li>
                        <span class="item_name" style="width:120px;"></span>
                        <input type="submit" class="link_btn"/>
                    </li>
                </ul>
            </section>
        </form>
    </div>
</section>

{% endblock %}

blog/templates/back/user_list.html
{% extends 'back/base_main.html' %}

{% block title %}
    用户信息
{% endblock %}

{% block content %}

<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">用户信息列表</h2>
        </div>
        <table class="table">
            <tr>
                <th>用户名</th>
                <th>注册时间</th>
                <th>是否可用</th>
            </tr>
            {% for user in users %}
                <tr>
                    <td class="center">
                        {{ user.username }}
                    </td>

                    <td class="center">
                        {{ user.create_time }}
                    </td>
                    <td class="center">
                        {% if user.is_delete == 0 %}
                            可用
                        {% else %}
                            不可用
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
</section>

{% endblock %}